### ISSUE TITLE
Any plans to support OS X?

### ISSUE THREAD

**Issue by iBicha** [sourcey/webrtc-precompiled-builds#2]

**Comment by auscaster** [comment]
Hi Brahim, no plans at this point since I dont have an apple system for
testing, although a PR for this would be very welcome! The changes would be
minimal due to similarities with linux.

**Comment by iBicha** [comment]
@auscaster I just finished a build, but I couldn't push it since it exceeds 100mb limit.
`¯\_(ツ)_/¯ `
  
  I'll leave this release here for anyone who need it https://github.com/iBicha/webrtc-precompiled-builds/releases/tag/r21522

**Comment by iBicha** [comment]
I'll close this for now, feel free to reopen if needed
